version: '3.8'

services:
  llm-proxy:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    ports:
      - "8000:8000"
      - "11434:11434"
    environment:
      - ENABLE_SEMANTIC_CLASSIFICATION=false
      - ENABLE_STREAMING=true
      - ENABLE_MODEL_WARMUP=true
      - MAX_MEMORY_MB=8192
      - DEBUG=false
    volumes:
      - ./data/models:/root/.ollama
      - ./data/cache:/app/cache
      - ./data/logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 180s

  # Optional Redis for distributed caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

volumes:
  redis_data:
